# Generated by Django 2.2.5 on 2020-09-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200916_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_secert',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
